name: Auto Reply to New Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;
            const message = `
            Thank you for raising this issue! Our team will review it soon. 

            For more queries, discussions, or approval of requests, please join the Discord server: [Discord Link](https://discord.com/invite/Yn9g6KuWyA)
            `;
            await github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
